<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'mineichen\\entitymanager\\action\\action' => '/Actions/Actions.php',
                'mineichen\\entitymanager\\action\\create' => '/Actions/Create.php',
                'mineichen\\entitymanager\\action\\delete' => '/Actions/Delete.php',
                'mineichen\\entitymanager\\action\\factory' => '/Actions/Factory.php',
                'mineichen\\entitymanager\\action\\plugin\\collection' => '/Actions/Plugin/Collection.php',
                'mineichen\\entitymanager\\action\\plugin\\container' => '/Actions/Plugin/Container.php',
                'mineichen\\entitymanager\\action\\plugin\\plugin' => '/Actions/Plugin/Plugin.php',
                'mineichen\\entitymanager\\action\\update' => '/Actions/Update.php',
                'mineichen\\entitymanager\\actionprioritygenerator' => '/ActionPriorityGenerator.php',
                'mineichen\\entitymanager\\configfactory' => '/Factory/ConfigManagerFactory.php',
                'mineichen\\entitymanager\\dependencyaware' => '/DependencyAware.php',
                'mineichen\\entitymanager\\entitymanager' => '/EntityManager.php',
                'mineichen\\entitymanager\\exception' => '/Exception.php',
                'mineichen\\entitymanager\\loader' => '/Repositories/Loader.php',
                'mineichen\\entitymanager\\observer\\asarray\\generator' => '/EntityObserver/asArray/Generator.php',
                'mineichen\\entitymanager\\observer\\asarray\\observable' => '/EntityObserver/asArray/Observable.php',
                'mineichen\\entitymanager\\observer\\asarray\\observer' => '/EntityObserver/asArray/EntityObserver.phper.php',
                'mineichen\\entitymanager\\observer\\entitytrait' => '/Repositories/EntityTrait.php',
                'mineichen\\entitymanager\\observer\\generator' => '/EntityObserver/Generator.php',
                'mineichen\\entitymanager\\observer\\generatorexception' => '/EntityObserver/GeneratorException.php',
                'mineichen\\entitymanager\\observer\\observer' => '/EntityObserver/EntityObserver.phper.php',
                'mineichen\\entitymanager\\proxy\\complementable' => '/Proxy/Complementable.php',
                'mineichen\\entitymanager\\proxy\\complementer' => '/Proxy/Complementer.php',
                'mineichen\\entitymanager\\proxy\\exception' => '/Proxy/Exception.php',
                'mineichen\\entitymanager\\proxy\\lazyload' => '/Proxy/LazyLoad.php',
                'mineichen\\entitymanager\\proxy\\notloaded' => '/Proxy/NotLoaded.php',
                'mineichen\\entitymanager\\proxy\\simplenotloaded' => '/Proxy/SimpleNotLoaded.php',
                'mineichen\\entitymanager\\repository\\identitymap' => '/Repositories/IdentityMap.php',
                'mineichen\\entitymanager\\repository\\managable' => '/Repositories/Managable.php',
                'mineichen\\entitymanager\\repository\\repository' => '/Repositories/Repository.php',
                'mineichen\\entitymanager\\repository\\repositorysandbox' => '/Repositories/RepositorySandbox.php',
                'mineichen\\entitymanager\\repositoryexception' => '/Repositories/RepositoryException.php',
                'mineichen\\entitymanager\\repositoryfactory' => '/Factory/RepositoryFactory.php',
                'mineichen\\entitymanager\\saver' => '/Repositories/Saver.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd